spring:
  application:
    name: demo_spring
  datasource:
    url: jdbc:mysql://localhost:30306/shopdevgo
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    port: 465
    host: smtp.gmail.com
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

