version: '1'
services:
  mysql:
    image: mysql:latest
    container_name: demo_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: shopdevgo
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: root1234
    ports:
      - "30306:3306"